# Generated by Django 3.2.5 on 2021-07-10 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210711_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='relatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative', to='myapp.user')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myapp.user')),
            ],
        ),
    ]
