# Generated by Django 3.2.5 on 2021-07-10 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210711_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images_dataset',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='relatives',
            old_name='relative_id',
            new_name='relative',
        ),
        migrations.RenameField(
            model_name='relatives',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='post_images',
            name='post_id',
        ),
        migrations.AddField(
            model_name='post_images',
            name='post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.post'),
        ),
        migrations.AlterField(
            model_name='images_dataset',
            name='image_url',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='post_images',
            name='image_dir',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
