# Generated by Django 3.2.5 on 2021-07-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_account_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=45, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.DeleteModel(
            name='account',
        ),
    ]
