# Generated by Django 3.2.5 on 2021-07-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
