# Generated by Django 3.2.5 on 2021-07-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_dir',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='post_images',
        ),
    ]
