# Generated by Django 3.2.5 on 2021-07-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20210711_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='case',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.CreateModel(
            name='notfications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
                ('content', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
