# Generated by Django 3.2.5 on 2021-07-12 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20210712_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notfications',
            name='content',
        ),
        migrations.RemoveField(
            model_name='notfications',
            name='type',
        ),
        migrations.AddField(
            model_name='notfications',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 17, 14, 19, 116880)),
        ),
        migrations.AddField(
            model_name='notfications',
            name='smallDescription',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 17, 14, 19, 115882)),
        ),
    ]
