# Generated by Django 3.2.5 on 2021-07-13 16:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20210712_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notfications',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 18, 59, 36, 344873)),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 18, 59, 36, 343878)),
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver_id', to='myapp.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='myapp.user')),
            ],
        ),
    ]
