# Generated by Django 3.2.5 on 2021-07-16 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20210713_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images_dataset',
            name='image_url',
        ),
        migrations.AddField(
            model_name='images_dataset',
            name='image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='notfications',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 30, 43, 727657)),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 30, 43, 727657)),
        ),
    ]
