# Generated by Django 3.2.5 on 2021-07-26 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20210718_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notfications',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 4, 15, 0, 914938)),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 4, 15, 0, 913938)),
        ),
    ]
