# Generated by Django 3.2.5 on 2021-07-26 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20210726_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_view',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='notfications',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 9, 4, 55, 743137)),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 9, 4, 55, 743137)),
        ),
    ]
